name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: How would you like to use this feature? Show example code.
      render: typescript
      placeholder: |
        import { newFeature } from '@kitium/detector';

        const result = newFeature();
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I considered...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      multiple: false
      options:
        - Platform Detection
        - Framework Detection
        - Browser Detection
        - Capability Detection
        - Performance Improvement
        - Developer Experience
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      multiple: false
      options:
        - Critical (blocking my work)
        - High (important for my use case)
        - Medium (would be nice to have)
        - Low (not urgent)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help
      placeholder: I need this feature because...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature would be useful to other users, not just me
          required: true
        - label: I am willing to help implement this feature
          required: false
